controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_test_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters: {}

front_test_controller:
  ros__parameters:
    joints: ["FL_hip_joint", "FL_uleg_joint", "FL_lleg_joint",
             "FR_hip_joint", "FR_uleg_joint", "FR_lleg_joint"]
