controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Broadcaster d'état des joints
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Contrôleurs individuels (utilisent JointGroupPositionController mais pour 1 joint chacun)
    FR_hip_joint_controller:
      type: position_controllers/JointGroupPositionController
    FL_hip_joint_controller:
      type: position_controllers/JointGroupPositionController
    BR_hip_joint_controller:
      type: position_controllers/JointGroupPositionController
    BL_hip_joint_controller:
      type: position_controllers/JointGroupPositionController

    FR_uleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    FL_uleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    BR_uleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    BL_uleg_joint_controller:
      type: position_controllers/JointGroupPositionController

    FR_lleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    FL_lleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    BR_lleg_joint_controller:
      type: position_controllers/JointGroupPositionController
    BL_lleg_joint_controller:
      type: position_controllers/JointGroupPositionController

# Paramètres individuels des contrôleurs
FR_hip_joint_controller:
  ros__parameters:
    joints:
      - "FR_hip_joint"
    interface_name: "position"

FL_hip_joint_controller:
  ros__parameters:
    joints:
      - "FL_hip_joint"
    interface_name: "position"

BR_hip_joint_controller:
  ros__parameters:
    joints:
      - "BR_hip_joint"
    interface_name: "position"

BL_hip_joint_controller:
  ros__parameters:
    joints:
      - "BL_hip_joint"
    interface_name: "position"

FR_uleg_joint_controller:
  ros__parameters:
    joints:
      - "FR_uleg_joint"
    interface_name: "position"

FL_uleg_joint_controller:
  ros__parameters:
    joints:
      - "FL_uleg_joint"
    interface_name: "position"

BR_uleg_joint_controller:
  ros__parameters:
    joints:
      - "BR_uleg_joint"
    interface_name: "position"

BL_uleg_joint_controller:
  ros__parameters:
    joints:
      - "BL_uleg_joint"
    interface_name: "position"

FR_lleg_joint_controller:
  ros__parameters:
    joints:
      - "FR_lleg_joint"
    interface_name: "position"

FL_lleg_joint_controller:
  ros__parameters:
    joints:
      - "FL_lleg_joint"
    interface_name: "position"

BR_lleg_joint_controller:
  ros__parameters:
    joints:
      - "BR_lleg_joint"
    interface_name: "position"

BL_lleg_joint_controller:
  ros__parameters:
    joints:
      - "BL_lleg_joint"
    interface_name: "position"
