controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    openDog_controller:
      type: forward_command_controller/ForwardCommandController

openDog_controller:
  ros__parameters:
    joints:
      - FR_hip_joint
      - FR_uleg_joint
      - FR_lleg_joint
      - FL_hip_joint
      - FL_uleg_joint
      - FL_lleg_joint
      - BR_hip_joint
      - BR_uleg_joint
      - BR_lleg_joint
      - BL_hip_joint
      - BL_uleg_joint
      - BL_lleg_joint
      
    interface_name: position
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort
    # command_interfaces:
    #   - position

    # state_interfaces:
    #   - position
    #   - velocity

    # state_publish_rate: 100.0 # Defaults to 50
    # action_monitor_rate: 20.0 # Defaults to 20

    # allow_partial_joints_goal: false # Defaults to false
    # open_loop_control: false
    # allow_integration_in_goal_trajectories: true
    # constraints:
    # stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    # goal_time: 0.0 # Defaults to 0.0 (start immediately)
    