<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>odrive_hardware_layer</name>
  <version>0.0.1</version>
  <description>
    ODrive CAN hardware interface plugin for ros2_control.
    Controls ODrive v3.6 motor controllers over SocketCAN (can0)
    using ODrive CANSimple protocol.
    Supports 6 ODrives with 2 motors each (12 motors total).
  </description>
  <maintainer email="ahsan.ali199812@gmail.com">ahsan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp_lifecycle</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>